[package]
name = "breakgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.23"
apres = "0.3.4"
quick-csv = "0.1.6"